name: scrap
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.10.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.0.0
  isolate: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.scrap
        pluginClass: ScrapPlugin
      ios:
        pluginClass: ScrapPlugin
